server:
  servlet:
    context-path: /web

spring:
  datasource:
#    oracle:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      url: jdbc:oracle:Thin:@localhost:1521:ORCL
#      username: scott
#      password: root
#    mysql:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/oa_hj_db
#      username: root
#      password: root

    type: com.alibaba.druid.pool.DruidDataSource