server:
  servlet:
    context-path: /web

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/oa_hj_db
      username: root
      password: root
